# Description: Build OpenWrt using GitHub Actions

name: OpenWrt Builder

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-23.05
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: openwrt_config
  DIY_P1_SH: diy_feeds.sh
  DIY_P2_SH: diy_host.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get clean


    - name: Clone source code
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH $GITHUB_WORKSPACE/openwrt
